import NavbarComponent from "@/components/navbar/navbar"
import SidebarComponent from "@/components/sidebar/sidbarComponent"
  
export const metadata = {
  title: 'Computer Shop',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="flex flex-col w-full scrollbar-hide">
        <body className="flex flex-col w-full min-h-screen">
            <header>
              <NavbarComponent/>
            </header>

            <main className="flex flex-grow h-full w-full justify-between">
              <div>
                <SidebarComponent/>
              </div>
              
              <div className="w-full flex flex-grow items-start justify-center"> 
                  {children}
              </div>
              
            </main>
        </body>
    </html>
  )
}
